volumes:
  server_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/var/hugotech/db"
  statics:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/var/hugotech/statics"
  media:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/var/hugotech/media"

services:
  server-init:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      DJANGO_SUPERUSER_PASSWORD: "3$$KDZm_*3W02"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "random@noexist.xyz"
    volumes:
      - server_db:/app/db/
      - statics:/app/static/
      - media:/app/media/
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "source activate bell_scheduler && python manage.py migrate && python manage.py collectstatic --noinput",
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  server:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      DJANGO_SUPERUSER_PASSWORD: "3$$KDZm_*3W02"
      DJANGO_SUPERUSER_USERNAME: "admin"
    volumes:
      - server_db:/app/db/
      - media:/app/media/
    devices:
      - /dev/gpiochip0
      - /dev/snd
    privileged: true
    ports:
      - "8000:8000"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "source activate bell_scheduler && granian app.asgi:application --host 0.0.0.0 --workers 4 --port 8000 --interface asgi",
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    depends_on:
      server-init:
        condition: service_completed_successfully
    restart: always

  play:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      TZ: "Europe/Bratislava"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "source activate bell_scheduler && python manage.py play",
      ]
    volumes:
      - server_db:/app/db/
      - media:/app/media/
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie  
    devices:
      - /dev/gpiochip0
      - /dev/snd
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    depends_on:
      server-init:
        condition: service_completed_successfully
    restart: always
