# Generated by Django 5.2 on 2025-06-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, null=True)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, null=True)),
                ('language', models.CharField(max_length=2)),
                ('text', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
                ('bell', models.BooleanField()),
                ('library', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bell_scheduler.library')),
                ('track', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bell_scheduler.track')),
            ],
        ),
    ]
