# Generated by Django 5.2 on 2025-06-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bell_scheduler.library'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bell_scheduler.track'),
        ),
    ]
