# Generated by Django 5.2 on 2025-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0002_alter_lesson_library_alter_lesson_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(),
        ),
    ]
