# Generated by Django 5.2 on 2025-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0003_lesson_id_alter_lesson_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='media',
            field=models.FileField(null=True, upload_to='libraries'),
        ),
        migrations.AddField(
            model_name='track',
            name='media',
            field=models.FileField(null=True, upload_to='tracks'),
        ),
    ]
