# Generated by Django 5.2 on 2025-06-12 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0004_library_media_track_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='library',
            name='path',
        ),
        migrations.RemoveField(
            model_name='track',
            name='path',
        ),
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
