# Generated by Django 5.2 on 2025-06-12 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0005_rename_text_track_description_remove_library_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='media',
        ),
        migrations.AddField(
            model_name='library',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='libraries')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bell_scheduler.library')),
            ],
        ),
    ]
