# Generated by Django 5.2 on 2025-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0006_remove_library_media_library_path_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
