# Generated by Django 5.2 on 2025-06-12 19:34

import bell_scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0008_alter_library_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, null=True, path=bell_scheduler.models.library_path),
        ),
    ]
