# Generated by Django 5.2 on 2025-06-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0010_alter_library_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='language',
        ),
    ]
