# Generated by Django 5.2 on 2025-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0011_remove_track_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='bell',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
