# Generated by Django 5.2 on 2025-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0012_track_bell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('playWeekend', models.BooleanField()),
                ('playHoliday', models.BooleanField()),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
