# Generated by Django 5.2 on 2025-06-21 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bell_scheduler', '0013_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bellPlaySeconds',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='pinBeforeSeconds',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='songPlaySeconds',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='trackPlaySeconds',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
